name: Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install GHDL
      run: |
        sudo apt-get install ghdl
    - name: Install VUnit
      run: |
        python -m pip install vunit_hdl
    - name: Run tests
      run: |
        cd vhdl
        python run.py --gtkwave-fmt ghw
        cd ..
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: waveforms
        path: vhdl/vunit_out/**/*.ghw

  page-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: waveforms
    - name: List contents
      run: |
        ls -alrt
        python pagebuild/pagebuild.py
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: html
  # Deploy job
  deploy:
    needs: page-build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
